---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: insights-results-aggregator-cleaner
  namespace: obsint-processing-tenant
  annotations:
    # This stub annotation is needed until KFLUXBUGS-1300 is resolved.
    hello: world
spec:
  displayName: insights-results-aggregator-cleaner
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: insights-results-aggregator-cleaner
  namespace: obsint-processing-tenant
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
spec:
  application: insights-results-aggregator-cleaner
  componentName: insights-results-aggregator-cleaner
  source:
    git:
      revision: main
      url: https://github.com/RedHatInsights/insights-results-aggregator-cleaner
      dockerfileUrl: Dockerfile
      context: ./
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-insights-results-aggregator-cleaner-insights-results-aggregator-cleaner
  namespace: obsint-processing-tenant
  labels:
    appstudio.redhat.com/application: insights-results-aggregator-cleaner
    appstudio.redhat.com/component: insights-results-aggregator-cleaner
spec:
  image:
    name: obsint-processing-tenant/insights-results-aggregator-cleaner/insights-results-aggregator-cleaner
    visibility: public
