---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: io-gathering-service
  namespace: obsint-processing-tenant
  annotations:
    # This stub annotation is needed until KFLUXBUGS-1300 is resolved.
    hello: world
spec:
  displayName: io-gathering-service
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: io-gathering-service
  namespace: obsint-processing-tenant
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
spec:
  application: io-gathering-service
  componentName: io-gathering-service
  source:
    git:
      revision: main
      url: https://github.com/RedHatInsights/insights-operator-gathering-conditions-service
      dockerfileUrl: Dockerfile
      context: ./
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-io-gathering-service-io-gathering-service
  namespace: obsint-processing-tenant
  labels:
    appstudio.redhat.com/application: io-gathering-service
    appstudio.redhat.com/component: io-gathering-service
spec:
  image:
    name: obsint-processing-tenant/io-gathering-service/io-gathering-service
    visibility: public
