apiVersion: projctl.konflux.dev/v1beta1
kind: Project
metadata:
  name: file-based-catalog
spec:
  displayName: Multi-version project for the file-based catalog of the CLI Manager
  description: |
    Multi-version project for the file-based catalog of the CLI Manager
