apiVersion: projctl.konflux.dev/v1beta1
kind: ProjectDevelopmentStream
metadata:
  name: cli-manager-operator-fbc-v4-17
  namespace: clio-wrklds-pipeline-tenant
spec:
  project: clio-wrklds-pipeline-tenant
  template:
    name: cli-manager-operator-fbc-dst
    values:
    - name: version
      value: "4.17"
    - name: versionName
      value: v4-17
