kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
# Naming: <API_GROUP>/<KIND_PLURAL>/<METADATA_NAME>
resources:
  - appstudio.redhat.com/releaseplans/cli-manager-operator-release-as-operator

