apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: "true"
  labels:
    appstudio.redhat.com/application: insights-results-aggregator-cleaner
    appstudio.redhat.com/component: insights-results-aggregator-cleaner
  name: imagerepository-for-insights-results-aggregator-cleaner-insights-results-aggregator-cleaner
  namespace: obsint-processing-tenant
spec:
  image:
    name: obsint-processing-tenant/insights-results-aggregator-cleaner/insights-results-aggregator-cleaner
    visibility: public
