apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  annotations:
    hello: world
  name: insights-results-aggregator-cleaner
  namespace: obsint-processing-tenant
spec:
  displayName: insights-results-aggregator-cleaner
